# -*- coding: utf-8 -*-
"""Script .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WJI_1obX3VDuZ2K7hrhfB5ZE8NcHgD3f
"""

import numpy as np 
import pandas as pd

import matplotlib.pyplot as plt 
import seaborn as sns

df = pd.read_csv("winequality.csv")
df.head()

df['quality_labels'] = df['quality'].apply(lambda value: 'low' 
                                                if value <= 5 else 'medium' 
                                                if value < 8 else 'high' )

df['quality_labels'] = pd.Categorical(df['quality_labels'], 
                                        categories=['low', 'medium', 'high'])

"""## Histogram """

f, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(12, 4))
f.suptitle("Distributon of Wine Quality", size=14)
f.subplots_adjust(top=0.85, wspace=0.3)

sns.histplot(df['quality'], 
                bins=5, ax=ax1)
ax1.set_xlabel("Wine Quality Score", size=12, alpha=0.8)

sns.countplot(x='quality_labels',data=df, ax=ax2)
ax2.set_xlabel("Wine Quality Labels", size=12, alpha=0.8)

plt.show()

"""## Univariate """

df.hist(bins=12, grid=False, figsize=(12, 10), xlabelsize=0)
plt.title('Univariate Analysis') 
plt.show()

sns.histplot( x = df["volatile acidity"],     
             bins = 10,
             cbar = True,
             kde = True,
             color = "#A163CF").set(title = "Distribution of 'volatile_acidity'")

sns.histplot( x = df["alcohol"],    
             bins = 10,
             cbar = True,
             kde = True,
             color = "#A163CF").set(title = "Distribution of 'alcohol'")

"""## Heatmap """

corr = df.corr()

# plot
plt.figure(figsize=(12, 6))
sns.heatmap(round(corr, 2), 
            annot=True, cmap='coolwarm', linewidths=1, fmt='.2f')
plt.title("Correlation plot", size=14, pad=10)
plt.show()

